arch: ppc64le
  
dist: 
  - xenial
  - bionic

service: docker

script:
  - #docker run -a stdin -a stdout -a stderr -u root -v $PWD:/home/travis/:rw,z ubuntu:16.04 bash /home/travis/install-conda.sh
  - docker run -a stdin -a stdout -a stderr -u root ubuntu:18.04 bash -c 'apt update -y && apt install -y git'
  - docker run -a stdin -a stdout -a stderr -u root centos:7 bash -c 'yum update -y && yum install -y git'
