arch: ppc64le
  
dist: bionic

service: docker

script:
  - #docker run -a stdin -a stdout -a stderr -u root -v $PWD:/home/travis/:rw,z ubuntu:16.04 bash /home/travis/install-conda.sh
  - docker run -a stdin -a stdout -a stderr -u root ubuntu:18.04 "/usr/bin/apt update -y && /usr/bin/apt install build-essential -y"
